[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
binary_option = "ATvmQTJT6JV9eYvBeyDacN9tGUKA4P5ykmxF9zK49CFr"

[programs.testnet]
binary_option = "ATvmQTJT6JV9eYvBeyDacN9tGUKA4P5ykmxF9zK49CFr"

[programs.devnet]
binary_option = "ATvmQTJT6JV9eYvBeyDacN9tGUKA4P5ykmxF9zK49CFr"

[registry]
url = "https://api.apr.dev"



[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
